"""Filesystem tools package re-exporting all submodules for modularity."""

from alfa.tools.filesystem.core_file import (
    _MAX_EDIT_FILE_BYTES,
    _py_syntax_guard,
    _resolve_host_path,
    apply_unified_diff,
    edit_file_precise,
    read_local_file,
    write_local_file,
)
from alfa.tools.filesystem.search import (
    compress_folder_to_zip,
    find_user_files,
    git_operations,
    grep_workspace,
    search_workspace_files,
    send_file_to_chat,
)
from alfa.tools.filesystem.code_index import (
    _CODE_CHUNK_LINES,
    _CODE_INDEX_DB,
    _CODE_INDEX_MAX_CHUNKS,
    _CODE_INDEX_SKIP_DIRS,
    _chunk_code_lines,
    _code_index_connect,
    _index_freshness,
    _index_one_file,
    _iter_code_files,
    index_codebase,
    search_codebase,
)
from alfa.tools.filesystem.office_convert import (
    libreoffice_convert_document,
    libreoffice_create_document,
    libreoffice_extract_document_text,
    libreoffice_render_page_previews,
    markitdown_convert_document,
)
from alfa.tools.filesystem.vault import (
    vault_delete_secret,
    vault_get_secret,
    vault_list_secrets,
    vault_store_secret,
)

# Re-export git worktrees, LSP, and Google Drive integrations
from git_sandbox import (
    git_worktree_sandbox_create,
    git_worktree_sandbox_list,
    git_worktree_sandbox_rollback,
    git_worktree_sandbox_verify_and_merge,
)
from lsp_code_intelligence import (
    lsp_analyze_module_hierarchy,
    lsp_find_symbol_definition,
    lsp_find_symbol_references,
)
from alfa.integrations.gdrive import (
    _detect_gdrive_auth_mode,
    _get_default_gdrive_folder_id,
    _get_gdrive_service,
    gdrive_create_folder,
    gdrive_download_file,
    gdrive_list_files,
    gdrive_oauth_exchange_code,
    gdrive_oauth_get_auth_url,
    gdrive_oauth_login,
    gdrive_oauth_logout,
    gdrive_save_oauth_client_secret,
    gdrive_status,
    gdrive_sync_to_second_brain,
    gdrive_upload_file,
)

__all__ = [
    "_MAX_EDIT_FILE_BYTES",
    "_py_syntax_guard",
    "_resolve_host_path",
    "read_local_file",
    "write_local_file",
    "edit_file_precise",
    "apply_unified_diff",
    "search_workspace_files",
    "grep_workspace",
    "find_user_files",
    "compress_folder_to_zip",
    "send_file_to_chat",
    "git_operations",
    "_CODE_INDEX_DB",
    "_CODE_INDEX_MAX_CHUNKS",
    "_CODE_CHUNK_LINES",
    "_CODE_INDEX_SKIP_DIRS",
    "_code_index_connect",
    "_index_freshness",
    "_iter_code_files",
    "_chunk_code_lines",
    "_index_one_file",
    "index_codebase",
    "search_codebase",
    "markitdown_convert_document",
    "libreoffice_convert_document",
    "libreoffice_render_page_previews",
    "libreoffice_create_document",
    "libreoffice_extract_document_text",
    "vault_store_secret",
    "vault_get_secret",
    "vault_list_secrets",
    "vault_delete_secret",
    "git_worktree_sandbox_create",
    "git_worktree_sandbox_list",
    "git_worktree_sandbox_rollback",
    "git_worktree_sandbox_verify_and_merge",
    "lsp_analyze_module_hierarchy",
    "lsp_find_symbol_definition",
    "lsp_find_symbol_references",
    "_detect_gdrive_auth_mode",
    "_get_default_gdrive_folder_id",
    "_get_gdrive_service",
    "gdrive_create_folder",
    "gdrive_download_file",
    "gdrive_list_files",
    "gdrive_oauth_exchange_code",
    "gdrive_oauth_get_auth_url",
    "gdrive_oauth_login",
    "gdrive_oauth_logout",
    "gdrive_save_oauth_client_secret",
    "gdrive_status",
    "gdrive_sync_to_second_brain",
    "gdrive_upload_file",
]
