"""
ALFA Tools Documentation Summary.
Auto-generated summary for quick capability lookups without loading entire tools.py.
"""

TOOL_DESCRIPTIONS = {
    "add_recurring_task": "Schedule an autonomous recurring task or proactive watchdog (e.g. monitor server stats every 30m, check crypto price every 15m, daily tech news briefing every 1440m).",
    "affiliate_broadcast_deal": "Kirimkan penawaran diskon affiliate secara otomatis ke Telegram Channel atau broadcast WhatsApp (Dikelola oleh Code Crafter).",
    "affiliate_generate_viral_content": "Hasilkan paket copywriting viral lengkap: Script Video TikTok (Hook 3s, Story, CTA), Telegram Deals Card, WhatsApp Broadcast, dan Auto-Reply 'Spill Link' (Dikelola oleh Strategic Planner).",
    "affiliate_hunt_trending_products": "Riset tren produk dan kata kunci viral untuk niche affiliate Shopee / TikTok Shop (Dikelola oleh Researcher Prime).",
    "affiliate_list_campaigns": "Lihat rekap histori campaign dan script affiliate yang aktif (Dikelola oleh Alpha Lead).",
    "analyze_dataset_csv_json": "GOD MODE: Intelligent Dataset Analyzer & Visualizer.",
    "apply_unified_diff": "Apply a UNIFIED DIFF (format `diff -u` / git diff) to a single file with",
    "audit_network_security": "GOD MODE: Network Security & Port Sentinel.",
    "audit_website_security": "Conduct a Defensive Cybersecurity Audit on a website or API endpoint (Cyber Sentry):",
    "auto_diagnose_and_heal_system": "GOD MODE: Autonomous System Diagnostic & Self-Healing Engine.",
    "browser_capture_screenshot": "Take a screenshot of the current Camofox browser page and automatically send it to the Telegram chat.",
    "browser_click_element": "Click an interactive button, link, checkbox, or element on the active Camofox browser page by its reference.",
    "browser_close_tab": "Close the active or specified Camofox browser tab.",
    "browser_open_url": "Open a web page in the Camofox stealth browser engine and return its accessibility element tree snapshot.",
    "browser_type_text": "Type text into an input field or search bar on the active Camofox browser page.",
    "browser_use_autonomous_task": "BROWSER-USE AGENT: Autonomous AI browser agent that visually controls the browser,",
    "cancel_recurring_task": "Cancel and delete a scheduled recurring task or watchdog by its ID.",
    "capture_desktop_screenshot": "Capture an ultra-fast, high-resolution screenshot of the active Linux desktop screen.",
    "capture_webcam_frame": "Capture a live snapshot frame from the connected hardware webcam/camera (/dev/video0).",
    "check_subagent_status": "Check the execution status and report of a spawned background subagent by its task ID.",
    "clean_system_storage": "GOD MODE: Smart Linux Storage Cleaner & Optimizer.",
    "compress_folder_to_zip": "Compress an entire folder/directory into a ZIP archive and send it to Telegram.",
    "conduct_ai_meeting": "Jalankan SWARM EKSEKUSI LANGSUNG: agen bekerja nyata memakai tool (mode rapat/diskusi sudah dihapus).",
    "control_linux_hardware": "Control Linux laptop/server hardware, audio, screen lock, power, Wi-Fi, and media from Telegram.",
    "convert_media_format": "Convert any video or audio file to another format using ffmpeg (e.g. mp4 -> mp3, mkv -> mp4, wav -> ogg, flac -> mp3).",
    "crawl4ai_web_crawler": "CRAWL4AI ENGINE: Asynchronous LLM-first web crawler that converts complex web pages",
    "crawlee_web_scraper": "CRAWLEE SUITE: Industrial-grade web crawler pipeline with automatic request queueing,",
    "deep_research_topic": "GOD MODE: Autonomous Deep Multi-Source Research Engine.",
    "delete_dynamic_plugin": "Permanently delete a dynamic plugin tool from disk and unregister from memory.",
    "desktop_click_coordinate": "Simulate a hardware mouse click on specific pixel coordinates (X, Y) on the Linux desktop screen.",
    "desktop_launch_app": "Launch a Linux GUI software application in the background (e.g. 'code', 'brave-browser', 'spotify', 'nautilus').",
    "desktop_type_keys": "Type text or press keyboard shortcuts/hotkeys on the active Linux desktop window.",
    "download_file_from_url": "Download a file from a URL on the internet to the local computer and optionally send it to Telegram.",
    "edit_file_precise": "Edit a file with SURGICAL precision (opencode-style): replace an exact",
    "edit_image": "Edit, convert, or transform an image file using Pillow and send the result to Telegram.",
    "execute_bash_command": "Execute a Linux shell command SAFELY inside an isolated Docker sandbox by",
    "execute_python_sandbox": "Execute a Python script in an ISOLATED Docker container (default) with",
    "export_knowledge_base": "GOD MODE: Export Second Brain Knowledge Base.",
    "extract_and_link_knowledge": "GOD MODE: Semantic Knowledge Graph & Second Brain Linker.",
    "extract_audio_from_video": "Extract the audio track from a video file (.mp4, .mkv, .webm, .avi) into an MP3 file and send to Telegram.",
    "fetch_web_page_content": "Fetch and extract clean text and main content from a website/article URL.",
    "firecrawl_scrape_and_crawl": "FIRECRAWL SUITE: Intelligent web scraper and crawler optimized for LLM RAG pipelines.",
    "generate_excel_spreadsheet": "Generate an Excel (.xlsx) spreadsheet with styled headers, borders, and auto-adjusted columns, automatically sent to Telegram.",
    "generate_pdf_report": "Generate a modern, beautifully styled PDF document report with ReportLab and automatically send it to Telegram.",
    "generate_presentation_pptx": "Generate a clean PowerPoint presentation (.pptx) and send it directly to Telegram.",
    "generate_promo_video_from_images": "Generate video promosi produk otomatis format 9:16 (1080x1920) untuk TikTok / Reels / Shorts hanya dari foto produk.",
    "generate_secure_password": "Generate one or more cryptographically secure random passwords.",
    "get_pdf_output_dir": "Returns absolute path to ~/Dokumen/ALFA_PDF_TOOLS/<subfolder>/ and ensures it exists.",
    "get_system_stats": "Get real-time Linux system health metrics including CPU cores/frequencies, RAM, Swap,",
    "git_operations": "Perform Git operations on a local repository directly from Telegram.",
    "grep_workspace": "Search for text or regex pattern inside files across workspace.",
    "images_convert_to_pdf": "Gabungkan kumpulan file foto/gambar (JPG, PNG, WEBP) menjadi satu dokumen PDF rapi.",
    "index_codebase": "Build/refresh a full-text INDEX of a repository so later searches are fast",
    "ingest_document_to_vector_brain": "NEURAL VECTOR BRAIN: Ingests, chunks, embeds, and indexes a document or local file",
    "is_internal_sandbox_artifact": "True bila file adalah artefak infrastruktur sandbox (bukan hasil kerja",
    "is_source_code_file": "True bila file adalah kode sumber — tidak usah dikirim mentah ke chat;",
    "kill_process": "Terminate/kill a running process by PID number or process name.",
    "libreoffice_convert_document": "LIBREOFFICE SUITE: Universal Document Converter.",
    "libreoffice_create_document": "LIBREOFFICE SUITE: Create Professional Office Documents (Writer, Calc, Impress).",
    "libreoffice_extract_document_text": "LIBREOFFICE SUITE: Extract Text & Structure from Any Document.",
    "libreoffice_render_page_previews": "LIBREOFFICE SUITE: Document High-Res Page Preview Renderer.",
    "list_dynamic_plugins": "List all dynamically created and hot-loaded plugin tools currently available in the system.",
    "list_recurring_tasks": "List all active recurring tasks and watchdogs scheduled for the user.",
    "list_running_processes": "List currently running processes on the system, sorted by memory usage.",
    "list_vector_brain_documents": "NEURAL VECTOR BRAIN: List all documents and files currently indexed in the Semantic Vector Brain.",
    "list_wa_drive_uploads": "Daftar berkas (foto/PDF/dokumen) yang otomatis diunggah dari WhatsApp ke Google Drive.",
    "manage_api_keys": "Manage API keys and multi-provider endpoints (Gemini, OpenAI, Groq, OpenRouter, Anthropic, Ollama, NVIDIA NIM).",
    "manage_crontab_jobs": "GOD MODE: Real Linux OS Crontab Manager.",
    "manage_custom_agents": "Manage the Autonomous AI Agent Workforce (Society of Agents).",
    "manage_system_services": "GOD MODE: Linux Systemd Services Controller.",
    "manage_wa_sheets_bot": "ECOSYSTEM INTEGRATION: WhatsApp Google Sheets Bot Controller.",
    "marketplace_search_products": "Cari dan scrape katalog produk real dari marketplace (Shopee, TikTok Shop, Tokopedia) berdasarkan kata kunci pencarian.",
    "markitdown_convert_document": "MARKITDOWN SUITE: Convert any document (Office Word/PowerPoint/Excel, PDF, HTML, CSV, JSON, Audio)",
    "normalize_path": "Samakan path gaya Linux (/dev/shm/...) dengan lokasi fisiknya di Windows",
    "open_web_dashboard": "ALFA OS: Web Command Center Dashboard Controller.",
    "pdf_apply_watermark_text": "Tambahkan stempel watermark teks diagonal transparan ke setiap halaman PDF.",
    "pdf_compress_and_optimize": "Kompresi dan optimalkan ukuran file PDF dengan mereduksi stream konten dan metadata berlebih.",
    "pdf_convert_to_images": "Konversi seluruh halaman PDF menjadi gambar PNG resolusi tinggi.",
    "pdf_decrypt_password": "Buka kunci PDF yang terproteksi password dan simpan salinan tanpa password.",
    "pdf_encrypt_password": "Lindungi dan kunci file PDF dengan password menggunakan enkripsi kuat AES-256.",
    "pdf_extract_full_text": "Ekstrak teks lengkap dari dokumen PDF secara bersih dan terstruktur serta simpan salinan file .txt.",
    "pdf_insert_page_numbers": "Sematkan penomoran halaman otomatis pada dokumen PDF.",
    "pdf_inspect_metadata": "Periksa informasi teknis mendalam dari file PDF (jumlah halaman, versi PDF, ukuran file, enkripsi, metadata) dan simpan salinan JSON.",
    "pdf_merge_documents": "Gabungkan beberapa file PDF menjadi satu dokumen PDF utuh.",
    "pdf_rotate_pages": "Putar orientasi halaman PDF (90, 180, atau 270 derajat searah jarum jam).",
    "pdf_split_document": "Pecah file PDF per halaman atau berdasarkan rentang halaman tertentu (misal '1-3, 5, 8-10').",
    "proactive_ambient_agent_config": "GOD MODE: Configure Ambient Proactive Autonomous Engagement.",
    "proactive_system_guardian_config": "GOD MODE: Configure the Proactive System Guardian daemon.",
    "query_database": "Execute a SQL query on a local SQLite database file and return the results as a table.",
    "query_token_usage": "Laporan pemakaian token AI per API key (realtime dari dashboard vault).",
    "read_clipboard": "Read the current desktop clipboard content (Windows: PowerShell, Linux: wl-paste/xclip/xsel).",
    "read_local_file": "Read the text content of a local file on the system safely.",
    "record_desktop_screen": "Record the desktop screen as an MP4 video for a specified duration and send to Telegram.",
    "save_knowledge_memory": "Save or update an important fact, user preference, project detail, or note into persistent long-term memory.",
    "scan_local_network": "Scan connected local LAN devices, IP neighbors, and active gateways.",
    "schedule_reminder": "Schedule a future proactive reminder or alert that the bot will send directly to Telegram.",
    "scrape_custom_urls_batch": "Scrape any custom list of URLs with high-speed multi-threaded workers or Camoufox stealth browser.",
    "scrape_large_scale_batch": "Scraping paralel skala besar untuk puluhan hingga ribuan URL sekaligus dengan kecepatan sangat tinggi.",
    "scrape_real_product_data": "Scrape data produk real dari Shopee, TikTok Shop, Tokopedia, atau website manapun menggunakan Camoufox Anti-Detect Browser atau Fast TLS.",
    "scrapling_stealth_fetch": "SCRAPLING STEALTH SUITE: Ultra-fast stealth web scraper engineered to bypass Cloudflare,",
    "scrapy_spider_quick_scrape": "SCRAPY FAST ENGINE: High-throughput web crawler and structured item extractor.",
    "scrcpy_android_control": "SCRCPY & ADB ANDROID ENGINE: Control Android smartphones/tablets via USB or Wi-Fi.",
    "search_codebase": "Search an indexed repository semantically-by-keyword (FTS5 ranked).",
    "search_knowledge_memory": "Search the persistent long-term memory for previously saved facts, user preferences, or notes.",
    "search_workspace_files": "Search for files and directories matching a glob pattern (e.g. '*.py', '*.json', 'bot*').",
    "self_add_new_tool": "GOD MODE: Self-Evolution Engine — dynamically writes, compiles, sandbox-tests, and hot-loads",
    "self_restart_service": "GOD MODE: Self-Restart — the bot restarts its own systemd service to apply",
    "semantic_search_vector_brain": "NEURAL VECTOR BRAIN: Performs semantic similarity search (Hybrid RAG) across all permanent",
    "send_email": "Send an email via SMTP (supports Gmail, Outlook, custom SMTP servers).",
    "send_file_to_chat": "Send an existing file (document, PDF, photo, video, audio, ZIP, code script, data file)",
    "show_desktop_notification": "Show a native desktop popup notification across Linux, macOS, and Windows.",
    "spawn_background_subagent": "Spawn an autonomous background subagent worker to solve a complex, long-running task",
    "ssh_execute_command": "Execute a command on a remote Linux server via SSH and return the output.",
    "start_focus_session": "GOD MODE: Focus & Pomodoro Productivity Session.",
    "text_to_audio_file": "Generate a high-fidelity natural speech audio file (.mp3) from any long text or script",
    "translate_text": "Translate text between languages using Google Translate.",
    "universal_deep_scraper": "High-Volume Universal Pro Web Scraper:",
    "vault_delete_secret": "Permanently delete a secret from αlfa Secure Vault by ID.",
    "vault_get_secret": "Retrieve and decrypt a sensitive secret from αlfa Secure Vault using AES-256-GCM.",
    "vault_list_secrets": "List all stored secrets metadata in αlfa Secure Vault without exposing decrypted plaintext.",
    "vault_store_secret": "Encrypt and store a sensitive credential, API key, affiliate token, or secret note",
    "vision_click_target": "GOD MODE: Vision-guided autonomous computer use loop.",
    "web_search": "Perform a live web search using DuckDuckGo to get up-to-date real-time information, news, or facts.",
    "write_local_file": "Write or create a text file on the local system.",
    "write_to_clipboard": "Write/copy text to the desktop clipboard so it can be pasted (Ctrl+V) anywhere.",
}
