"""initial_schema

Revision ID: df0134acda10
Revises: 
Create Date: 2026-08-29 17:13:55.720711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df0134acda10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('prompt_instruction', sa.Text(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_tasks_user_id'), 'recurring_tasks', ['user_id'], unique=False)
    op.create_table('sub_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subagent_id', sa.String(length=50), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('agent_role', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_agents_subagent_id'), 'sub_agents', ['subagent_id'], unique=True)
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_timestamp'), 'token_usage', ['timestamp'], unique=False)
    op.create_index(op.f('ix_token_usage_user_id'), 'token_usage', ['user_id'], unique=False)
    op.create_table('vector_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('vector_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dynamic_plugins')
    op.drop_index(op.f('idx_subagent_user_status'), table_name='subagent_tasks')
    op.drop_table('subagent_tasks')
    op.drop_index(op.f('idx_aal_agent_ts'), table_name='agent_activity_logs')
    op.drop_table('agent_activity_logs')
    op.drop_table('agent_meetings')
    op.drop_table('system_settings')
    op.drop_table('knowledge_graph')
    op.drop_index(op.f('idx_atu_key'), table_name='api_token_usage')
    op.drop_index(op.f('idx_atu_ts'), table_name='api_token_usage')
    op.drop_table('api_token_usage')
    op.drop_index(op.f('idx_cron_user_next'), table_name='scheduled_cron_jobs')
    op.drop_table('scheduled_cron_jobs')
    op.alter_column('api_keys', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('api_keys', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('api_keys', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('api_keys', 'base_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('api_keys', 'default_model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('chat_history', sa.Column('chat_id', sa.String(length=255), nullable=False))
    op.add_column('chat_history', sa.Column('message_id', sa.Integer(), nullable=True))
    op.add_column('chat_history', sa.Column('model_used', sa.String(length=100), nullable=True))
    op.add_column('chat_history', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.alter_column('chat_history', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('chat_history', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('chat_history', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('chat_history', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('idx_ch_user_ts'), table_name='chat_history')
    op.create_index('idx_user_chat', 'chat_history', ['user_id', 'chat_id'], unique=False)
    op.create_index(op.f('ix_chat_history_chat_id'), 'chat_history', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.add_column('custom_agents', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('custom_agents', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('custom_agents', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('custom_agents', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('custom_agents', 'persona',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('custom_agents', 'system_instruction',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('custom_agents', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text("'gemini'"))
    op.alter_column('custom_agents', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True,
               existing_server_default=sa.text("'gemini-3.6-flash'"))
    op.alter_column('custom_agents', 'avatar_emoji',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'🤖'"))
    op.alter_column('custom_agents', 'color_theme',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'cyan'"))
    op.drop_constraint(None, 'custom_agents', type_='foreignkey')
    op.drop_column('custom_agents', 'is_enabled')
    op.drop_column('custom_agents', 'enable_tools')
    op.drop_column('custom_agents', 'api_key_id')
    op.add_column('focus_sessions', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('focus_sessions', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('focus_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('focus_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('focus_sessions', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=True)
    op.alter_column('focus_sessions', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('focus_sessions', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
    op.create_index(op.f('ix_focus_sessions_user_id'), 'focus_sessions', ['user_id'], unique=False)
    op.drop_column('focus_sessions', 'end_time')
    op.drop_column('focus_sessions', 'start_time')
    op.drop_column('focus_sessions', 'is_notified')
    op.drop_column('focus_sessions', 'chat_id')
    op.add_column('knowledge_memory', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('knowledge_memory', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('knowledge_memory', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('knowledge_memory', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('knowledge_memory', 'key_topic',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('knowledge_memory', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('knowledge_memory', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'general'"))
    op.drop_index(op.f('idx_km_user_topic'), table_name='knowledge_memory')
    op.create_index('idx_user_topic', 'knowledge_memory', ['user_id', 'key_topic'], unique=False)
    op.create_index(op.f('ix_knowledge_memory_user_id'), 'knowledge_memory', ['user_id'], unique=False)
    op.add_column('reminders', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('reminders', sa.Column('interval_minutes', sa.Integer(), nullable=True))
    op.add_column('reminders', sa.Column('sent', sa.Boolean(), nullable=True))
    op.alter_column('reminders', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('reminders', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('reminders', 'reminder_time',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('reminders', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('idx_rem_user_exec'), table_name='reminders')
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.drop_column('reminders', 'is_executed')
    op.drop_column('reminders', 'chat_id')
    op.add_column('user_settings', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user_settings', sa.Column('settings_json', sa.Text(), nullable=True))
    op.add_column('user_settings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               nullable=False)
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.drop_column('user_settings', 'system_prompt_override')
    op.drop_column('user_settings', 'model_name')
    op.drop_column('user_settings', 'voice_reply')
    op.add_column('vault_secrets', sa.Column('value', sa.Text(), nullable=False))
    op.alter_column('vault_secrets', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('vault_secrets', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('vault_secrets', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text("'api_key'"))
    op.alter_column('vault_secrets', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('vault_secrets', 'ciphertext')
    op.drop_column('vault_secrets', 'updated_at')
    op.drop_column('vault_secrets', 'nonce')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vault_secrets', sa.Column('nonce', sa.TEXT(), nullable=False))
    op.add_column('vault_secrets', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('vault_secrets', sa.Column('ciphertext', sa.TEXT(), nullable=False))
    op.alter_column('vault_secrets', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('vault_secrets', 'category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'api_key'"))
    op.alter_column('vault_secrets', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('vault_secrets', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('vault_secrets', 'value')
    op.add_column('user_settings', sa.Column('voice_reply', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('user_settings', sa.Column('model_name', sa.TEXT(), server_default=sa.text("'gemini-3.6-flash'"), nullable=True))
    op.add_column('user_settings', sa.Column('system_prompt_override', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_settings', 'updated_at')
    op.drop_column('user_settings', 'settings_json')
    op.drop_column('user_settings', 'id')
    op.add_column('reminders', sa.Column('chat_id', sa.INTEGER(), nullable=False))
    op.add_column('reminders', sa.Column('is_executed', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.create_index(op.f('idx_rem_user_exec'), 'reminders', ['user_id', 'is_executed'], unique=False)
    op.alter_column('reminders', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('reminders', 'reminder_time',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('reminders', 'user_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('reminders', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('reminders', 'sent')
    op.drop_column('reminders', 'interval_minutes')
    op.drop_column('reminders', 'is_recurring')
    op.drop_index(op.f('ix_knowledge_memory_user_id'), table_name='knowledge_memory')
    op.drop_index('idx_user_topic', table_name='knowledge_memory')
    op.create_index(op.f('idx_km_user_topic'), 'knowledge_memory', ['user_id', 'key_topic'], unique=False)
    op.alter_column('knowledge_memory', 'category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'general'"))
    op.alter_column('knowledge_memory', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('knowledge_memory', 'key_topic',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('knowledge_memory', 'user_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('knowledge_memory', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('knowledge_memory', 'created_at')
    op.drop_column('knowledge_memory', 'tags')
    op.add_column('focus_sessions', sa.Column('chat_id', sa.INTEGER(), nullable=False))
    op.add_column('focus_sessions', sa.Column('is_notified', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('focus_sessions', sa.Column('start_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('focus_sessions', sa.Column('end_time', sa.DATETIME(), nullable=False))
    op.drop_index(op.f('ix_focus_sessions_user_id'), table_name='focus_sessions')
    op.alter_column('focus_sessions', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'active'"))
    op.alter_column('focus_sessions', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('focus_sessions', 'title',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('focus_sessions', 'user_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('focus_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('focus_sessions', 'completed_at')
    op.drop_column('focus_sessions', 'started_at')
    op.add_column('custom_agents', sa.Column('api_key_id', sa.INTEGER(), nullable=True))
    op.add_column('custom_agents', sa.Column('enable_tools', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('custom_agents', sa.Column('is_enabled', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
    op.create_foreign_key(None, 'custom_agents', 'api_keys', ['api_key_id'], ['id'])
    op.alter_column('custom_agents', 'color_theme',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'cyan'"))
    op.alter_column('custom_agents', 'avatar_emoji',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'🤖'"))
    op.alter_column('custom_agents', 'model',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'gemini-3.6-flash'"))
    op.alter_column('custom_agents', 'provider',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'gemini'"))
    op.alter_column('custom_agents', 'system_instruction',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('custom_agents', 'persona',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('custom_agents', 'role',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('custom_agents', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('custom_agents', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('custom_agents', 'is_active')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_chat_id'), table_name='chat_history')
    op.drop_index('idx_user_chat', table_name='chat_history')
    op.create_index(op.f('idx_ch_user_ts'), 'chat_history', ['user_id', 'timestamp'], unique=False)
    op.alter_column('chat_history', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat_history', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('chat_history', 'user_id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('chat_history', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('chat_history', 'tokens_used')
    op.drop_column('chat_history', 'model_used')
    op.drop_column('chat_history', 'message_id')
    op.drop_column('chat_history', 'chat_id')
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('api_keys', 'default_model',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('api_keys', 'base_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('api_keys', 'provider',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('api_keys', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('api_keys', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('scheduled_cron_jobs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('prompt_instruction', sa.TEXT(), nullable=False),
    sa.Column('interval_minutes', sa.INTEGER(), server_default=sa.text('(60)'), nullable=False),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('last_run', sa.DATETIME(), nullable=True),
    sa.Column('next_run', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_cron_user_next'), 'scheduled_cron_jobs', ['user_id', 'next_run'], unique=False)
    op.create_table('api_token_usage',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('ts', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('provider', sa.TEXT(), nullable=False),
    sa.Column('model', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('key_id', sa.INTEGER(), nullable=True),
    sa.Column('key_label', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('context', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_atu_ts'), 'api_token_usage', ['ts'], unique=False)
    op.create_index(op.f('idx_atu_key'), 'api_token_usage', ['key_id'], unique=False)
    op.create_table('knowledge_graph',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('entity', sa.TEXT(), nullable=False),
    sa.Column('relation', sa.TEXT(), nullable=False),
    sa.Column('target_value', sa.TEXT(), nullable=False),
    sa.Column('category', sa.TEXT(), server_default=sa.text("'general'"), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity', 'relation')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('agent_meetings',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('topic', sa.TEXT(), nullable=False),
    sa.Column('participants', sa.TEXT(), nullable=False),
    sa.Column('dialogue_transcript', sa.TEXT(), nullable=False),
    sa.Column('consensus', sa.TEXT(), nullable=True),
    sa.Column('action_plan', sa.TEXT(), nullable=True),
    sa.Column('mode', sa.TEXT(), server_default=sa.text("'plan'"), nullable=True),
    sa.Column('execution_results', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'completed'"), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_activity_logs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('agent_id', sa.INTEGER(), nullable=True),
    sa.Column('agent_name', sa.TEXT(), nullable=False),
    sa.Column('action_type', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('tool_name', sa.TEXT(), nullable=True),
    sa.Column('tool_input', sa.TEXT(), nullable=True),
    sa.Column('tool_output', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'success'"), nullable=True),
    sa.Column('duration_ms', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_aal_agent_ts'), 'agent_activity_logs', ['agent_id', 'created_at'], unique=False)
    op.create_table('subagent_tasks',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.TEXT(), nullable=False),
    sa.Column('task_description', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'running'"), nullable=True),
    sa.Column('result', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_subagent_user_status'), 'subagent_tasks', ['user_id', 'status'], unique=False)
    op.create_table('dynamic_plugins',
    sa.Column('tool_name', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('code', sa.TEXT(), nullable=False),
    sa.Column('parameters_json', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=True),
    sa.Column('last_test_output', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('tool_name')
    )
    op.drop_table('vector_documents')
    op.drop_index(op.f('ix_token_usage_user_id'), table_name='token_usage')
    op.drop_index(op.f('ix_token_usage_timestamp'), table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index(op.f('ix_sub_agents_subagent_id'), table_name='sub_agents')
    op.drop_table('sub_agents')
    op.drop_index(op.f('ix_recurring_tasks_user_id'), table_name='recurring_tasks')
    op.drop_table('recurring_tasks')
    # ### end Alembic commands ###
