"""
Dynamic Plugin Tool: crypto_forex_live_rates
Description: Mengambil harga live cryptocurrency (BTC, ETH, SOL, BNB, DOGE) dan kurs valuta asing (USD, EUR, SGD, JPY ke IDR).
Auto-Generated by ALFA Self-Evolution Engine: 2026-08-21 17:23:05
"""

import os
import sys
import json
import math
import time
import subprocess
from typing import Dict, Any, List, Optional, Union

def crypto_forex_live_rates(symbols: str = 'BTC,ETH,SOL,BNB,DOGE', base_fiat: str = 'IDR') -> dict:
    """
    Cek harga crypto pasar global dan kurs mata uang asing ke Rupiah secara live.
    
    Args:
        symbols: Daftar simbol crypto dipisah koma (contoh: 'BTC,ETH,SOL,BNB,DOGE').
        base_fiat: Mata uang dasar untuk kurs forex (default: 'IDR').
    """
    import json
    import urllib.request
    
    symbol_map = {
        'BTC': 'bitcoin',
        'ETH': 'ethereum',
        'SOL': 'solana',
        'BNB': 'binancecoin',
        'DOGE': 'dogecoin',
        'XRP': 'ripple',
        'ADA': 'cardano',
        'AVAX': 'avalanche-2',
        'DOT': 'polkadot'
    }
    
    input_syms = [s.strip().upper() for s in symbols.split(',') if s.strip()]
    coingecko_ids = [symbol_map.get(s, s.lower()) for s in input_syms]
    
    crypto_data = {}
    forex_data = {}
    
    # 1. Fetch Real Live Crypto from CoinGecko Public API
    try:
        ids_str = ','.join(coingecko_ids)
        c_url = f'https://api.coingecko.com/api/v3/simple/price?ids={ids_str}&vs_currencies=usd,idr&include_24hr_change=true'
        req = urllib.request.Request(c_url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) ALFA-Agent/1.0'})
        with urllib.request.urlopen(req, timeout=8) as resp:
            raw_c = json.loads(resp.read().decode())
            for sym in input_syms:
                cg_id = symbol_map.get(sym, sym.lower())
                if cg_id in raw_c:
                    d = raw_c[cg_id]
                    crypto_data[sym] = {
                        'price_usd': d.get('usd', 0),
                        'price_idr': d.get('idr', 0),
                        'change_24h_usd_pct': round(d.get('usd_24h_change', 0) or 0, 2),
                        'change_24h_idr_pct': round(d.get('idr_24h_change', 0) or 0, 2)
                    }
    except Exception as e:
        crypto_data['error'] = f'CoinGecko query failed: {str(e)}'
        
    # 2. Fetch Live Forex Rates from Open Exchange Rates
    try:
        f_url = 'https://open.er-api.com/v6/latest/USD'
        req2 = urllib.request.Request(f_url, headers={'User-Agent': 'ALFA-Agent/1.0'})
        with urllib.request.urlopen(req2, timeout=6) as resp2:
            fd = json.loads(resp2.read().decode())
            rates = fd.get('rates', {})
            usd_idr = rates.get('IDR', 16200.0)
            forex_data = {
                'USD_IDR': round(usd_idr, 2),
                'EUR_IDR': round(usd_idr / rates.get('EUR', 1.0), 2) if rates.get('EUR') else 0,
                'SGD_IDR': round(usd_idr / rates.get('SGD', 1.0), 2) if rates.get('SGD') else 0,
                'JPY_IDR': round(usd_idr / rates.get('JPY', 1.0), 2) if rates.get('JPY') else 0,
                'last_updated_utc': fd.get('time_last_update_utc', '')
            }
    except Exception as e:
        forex_data['error'] = f'Forex API query failed: {str(e)}'
        
    return {
        'status': 'success',
        'crypto_prices': crypto_data,
        'forex_rates_idr': forex_data
    }
