"""
Dynamic Plugin Tool: crypto_forex_live_rates
Description: Mengambil harga live cryptocurrency (BTC, ETH, SOL, BNB, DOGE) dan kurs valuta asing (USD, EUR, SGD, JPY ke IDR).
Auto-Generated by ALFA Self-Evolution Engine: 2026-08-21 17:16:58
"""

import os
import sys
import json
import math
import time
import subprocess
from typing import Dict, Any, List, Optional, Union

def crypto_forex_live_rates(symbols: str = 'BTC,ETH,SOL,BNB', base_fiat: str = 'IDR') -> dict:
    """
    Cek harga crypto pasar global dan kurs mata uang asing ke Rupiah.
    
    Args:
        symbols: Daftar simbol crypto dipisah koma (contoh: 'BTC,ETH,SOL').
        base_fiat: Mata uang dasar untuk kurs forex (default: 'IDR').
    """
    import json
    import urllib.request
    
    crypto_data = {}
    forex_data = {}
    
    # 1. Fetch Crypto from Binance API
    sym_list = [s.strip().upper() for s in symbols.split(',') if s.strip()]
    for s in sym_list:
        try:
            pair = f'{s}USDT'
            url = f'https://api.binance.com/api/v3/ticker/24hr?symbol={pair}'
            req = urllib.request.Request(url, headers={'User-Agent': 'ALFA-Agent/1.0'})
            with urllib.request.urlopen(req, timeout=5) as resp:
                d = json.loads(resp.read().decode())
                crypto_data[s] = {
                    'price_usd': float(d.get('lastPrice', 0)),
                    'change_24h_pct': float(d.get('priceChangePercent', 0)),
                    'high_24h_usd': float(d.get('highPrice', 0)),
                    'low_24h_usd': float(d.get('lowPrice', 0)),
                    'volume_24h': round(float(d.get('volume', 0)), 2)
                }
        except Exception:
            pass
            
    # 2. Fetch Forex Exchange Rates from open API
    try:
        f_url = 'https://open.er-api.com/v6/latest/USD'
        req2 = urllib.request.Request(f_url, headers={'User-Agent': 'ALFA-Agent/1.0'})
        with urllib.request.urlopen(req2, timeout=5) as resp2:
            fd = json.loads(resp2.read().decode())
            rates = fd.get('rates', {})
            usd_idr = rates.get('IDR', 16200.0)
            forex_data = {
                'USD_IDR': round(usd_idr, 2),
                'EUR_IDR': round(usd_idr / rates.get('EUR', 1.0), 2) if rates.get('EUR') else 0,
                'SGD_IDR': round(usd_idr / rates.get('SGD', 1.0), 2) if rates.get('SGD') else 0,
                'JPY_IDR': round(usd_idr / rates.get('JPY', 1.0), 2) if rates.get('JPY') else 0
            }
            # Convert crypto to IDR
            for k in crypto_data:
                crypto_data[k]['price_idr'] = round(crypto_data[k]['price_usd'] * usd_idr, 0)
    except Exception:
        pass
        
    return {
        'status': 'success',
        'crypto_prices': crypto_data,
        'forex_rates_idr': forex_data
    }
