"""
Dynamic Plugin Tool: github_assistant
Description: Asisten GitHub pribadi via gh CLI: daftar repo, detail repo, kelola issue (lihat/buat/cari), pull request, dan notifikasi akun.
Auto-Generated by ALFA Self-Evolution Engine: 2026-08-22
"""

import os
import sys
import json
import time
import subprocess
from typing import Dict, Any, List, Optional, Union

def github_assistant(action: str = 'repos', repo: str = '', query: str = '', limit: int = 10) -> dict:
    """
    Asisten GitHub pribadi menggunakan gh CLI yang sudah terautentikasi.
    Aksi yang tersedia:
    - 'repos'        : daftar repository milik akun.
    - 'info'         : detail satu repository (bintang, fork, bahasa, dll).
    - 'issues'       : daftar issue terbuka pada sebuah repo.
    - 'create_issue' : buat issue baru; isi query dengan format 'Judul | Deskripsi'.
    - 'search'       : cari issue/PR pada repo berdasarkan kata kunci.
    - 'prs'          : daftar pull request terbuka pada sebuah repo.
    - 'notifikasi'   : notifikasi terbaru akun GitHub.
    
    Args:
        action: Salah satu dari: repos, info, issues, create_issue, search, prs, notifikasi.
        repo: Nama repo lengkap 'pemilik/nama' (kosong = repo proyek ALFA saat ini).
        query: Kata kunci pencarian (untuk search) atau 'Judul | Deskripsi' (untuk create_issue).
        limit: Jumlah maksimal hasil (1-50, default 10).
    """
    ACTIONS = {'repos', 'info', 'issues', 'create_issue', 'search', 'prs', 'notifikasi'}
    action = (action or 'repos').strip().lower()
    if action not in ACTIONS:
        return {"status": "error", "message": f"Aksi '{action}' tidak dikenal. Pilihan: {', '.join(sorted(ACTIONS))}."}

    limit = max(1, min(int(limit or 10), 50))

    def default_repo() -> str:
        if repo.strip():
            return repo.strip()
        try:
            project_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            res = subprocess.run(['git', '-C', project_dir, 'remote', 'get-url', 'origin'],
                                 capture_output=True, text=True, timeout=8)
            url = res.stdout.strip()
            for prefix in ('https://github.com/', 'git@github.com:'):
                if url.startswith(prefix):
                    return url[len(prefix):].replace('.git', '')
        except Exception:
            pass
        return ''

    def run_gh(args: List[str], timeout: int = 30):
        res = subprocess.run(['gh'] + args, capture_output=True, text=True, timeout=timeout)
        if res.returncode != 0:
            raise RuntimeError((res.stderr or 'perintah gh gagal').strip()[:300])
        return res.stdout

    def parse_json(out: str):
        out = out.strip() or '[]'
        return json.loads(out)

    try:
        # ── Aksi tanpa repo ──
        if action == 'repos':
            data = parse_json(run_gh([
                'repo', 'list', '--limit', str(limit),
                '--json', 'name,description,updatedAt,isPrivate,url,stargazerCount'
            ]))
            items = [{
                'nama': r.get('name'),
                'privat': bool(r.get('isPrivate')),
                'bintang': r.get('stargazerCount', 0),
                'deskripsi': (r.get('description') or '')[:120],
                'diperbarui': r.get('updatedAt'),
                'url': r.get('url'),
            } for r in data]
            return {"status": "success", "action": action, "jumlah": len(items),
                    "message": f"{len(items)} repository ditemukan.", "results": items}

        if action == 'notifikasi':
            data = parse_json(run_gh(['api', 'notifications'], timeout=20))
            items = [{
                'judul': (n.get('subject') or {}).get('title', ''),
                'tipe': (n.get('subject') or {}).get('type', ''),
                'repo': (n.get('repository') or {}).get('nameWithOwner', ''),
                'alasan': n.get('reason', ''),
                'waktu': n.get('updated_at', ''),
            } for n in data[:limit]]
            if not items:
                return {"status": "success", "action": action, "jumlah": 0,
                        "message": "Tidak ada notifikasi belum dibaca. 🎉"}
            return {"status": "success", "action": action, "jumlah": len(items),
                    "message": f"{len(items)} notifikasi.", "results": items}

        # ── Aksi dengan repo ──
        target = default_repo()
        if not target:
            return {"status": "error",
                    "message": "Repo tidak ditentukan dan tidak bisa dideteksi dari remote origin."}

        if action == 'info':
            data = parse_json(run_gh([
                'repo', 'view', target, '--json',
                'name,description,defaultBranchRef,diskUsage,pushedAt,url,stargazerCount,forkCount,primaryLanguage,licenseInfo'
            ]))
            return {"status": "success", "action": action,
                    "message": f"Detail {target}.",
                    "result": {
                        'nama': data.get('name'),
                        'deskripsi': data.get('description') or '',
                        'branch_utama': (data.get('defaultBranchRef') or {}).get('name', ''),
                        'bahasa': (data.get('primaryLanguage') or {}).get('name', ''),
                        'ukuran_kb': data.get('diskUsage'),
                        'bintang': data.get('stargazerCount'),
                        'fork': data.get('forkCount'),
                        'push_terakhir': data.get('pushedAt'),
                        'lisensi': ((data.get('licenseInfo') or {}).get('name', '')),
                        'url': data.get('url'),
                    }}

        if action == 'issues':
            data = parse_json(run_gh([
                'issue', 'list', '-R', target, '--state', 'open',
                '--limit', str(limit), '--json', 'number,title,url,labels,updatedAt'
            ]))
            items = [{
                'nomor': i.get('number'), 'judul': i.get('title'), 'url': i.get('url'),
                'label': [l.get('name', '') for l in i.get('labels', [])],
                'diperbarui': i.get('updatedAt'),
            } for i in data]
            msg = f"{len(items)} issue terbuka di {target}." if items else f"Tidak ada issue terbuka di {target}. 🎉"
            return {"status": "success", "action": action, "jumlah": len(items),
                    "message": msg, "results": items}

        if action == 'create_issue':
            raw = (query or '').strip()
            if '|' in raw:
                title, body = raw.split('|', 1)
            else:
                title, body = raw, ''
            title = title.strip()
            if not title:
                return {"status": "error",
                        "message": "Judul issue wajib. Format query: 'Judul | Deskripsi'."}
            args = ['issue', 'create', '-R', target, '-t', title]
            if body.strip():
                args += ['-b', body.strip()]
            url_out = run_gh(args, timeout=30).strip()
            return {"status": "success", "action": action,
                    "message": f"Issue dibuat di {target}: {title}",
                    "url": url_out}

        if action == 'search':
            q = (query or '').strip()
            if not q:
                return {"status": "error", "message": "Kata kunci pencarian wajib diisi."}
            data = parse_json(run_gh([
                'search', 'issues', q, '--repo', target, '--limit', str(limit),
                '--json', 'number,title,url,state'
            ], timeout=30))
            items = [{
                'nomor': i.get('number'), 'judul': i.get('title'),
                'status': i.get('state'), 'url': i.get('url'),
            } for i in data]
            return {"status": "success", "action": action, "jumlah": len(items),
                    "message": f"{len(items)} hasil untuk '{q}' di {target}.",
                    "results": items}

        if action == 'prs':
            data = parse_json(run_gh([
                'pr', 'list', '-R', target, '--limit', str(limit),
                '--json', 'number,title,url,author,updatedAt'
            ]))
            items = [{
                'nomor': p.get('number'), 'judul': p.get('title'), 'url': p.get('url'),
                'penulis': (p.get('author') or {}).get('login', ''), 'diperbarui': p.get('updatedAt'),
            } for p in data]
            msg = f"{len(items)} pull request terbuka di {target}." if items else f"Tidak ada PR terbuka di {target}."
            return {"status": "success", "action": action, "jumlah": len(items),
                    "message": msg, "results": items}

        return {"status": "error", "message": "Aksi tidak tertangani."}

    except subprocess.TimeoutExpired:
        return {"status": "error", "message": "GitHub timeout (lebih dari 30 detik)."}
    except FileNotFoundError:
        return {"status": "error", "message": "gh CLI tidak ditemukan di sistem ini."}
    except RuntimeError as re_err:
        return {"status": "error", "message": f"GitHub: {str(re_err)}"}
    except Exception as e:
        return {"status": "error", "message": f"github_assistant error: {str(e)}"}
