"""
Dynamic Plugin Tool: whois_dns_domain_lookup
Description: Menganalisis domain web: IP Address, DNS Records, Status SSL Certificate, dan Response Header server.
Auto-Generated by ALFA Self-Evolution Engine: 2026-08-21 17:16:59
"""

import os
import sys
import json
import math
import time
import subprocess
from typing import Dict, Any, List, Optional, Union

def whois_dns_domain_lookup(domain: str) -> dict:
    """
    Inspeksi intelijen domain, resolusi DNS, dan validitas sertifikat SSL HTTPS.
    
    Args:
        domain: Nama domain atau hostname (contoh: 'google.com', 'github.com').
    """
    import socket
    import ssl
    import urllib.request
    from datetime import datetime
    
    clean_domain = domain.replace('https://', '').replace('http://', '').split('/')[0].strip()
    results = {'domain': clean_domain}
    
    # 1. IP Resolution
    try:
        ip_list = socket.gethostbyname_ex(clean_domain)[2]
        results['ip_addresses'] = ip_list
    except Exception as e:
        results['ip_addresses'] = []
        results['ip_error'] = str(e)
        
    # 2. SSL Certificate Details & Expiration
    try:
        ctx = ssl.create_default_context()
        with ctx.wrap_socket(socket.socket(), server_hostname=clean_domain) as s:
            s.settimeout(5.0)
            s.connect((clean_domain, 443))
            cert = s.getpeercert()
            
            not_after_str = cert.get('notAfter', '')
            if not_after_str:
                expire_dt = datetime.strptime(not_after_str, '%b %d %H:%M:%S %Y %Z')
                days_left = (expire_dt - datetime.utcnow()).days
            else:
                days_left = None
                
            issuer = dict(x[0] for x in cert.get('issuer', []))
            subject = dict(x[0] for x in cert.get('subject', []))
            
            results['ssl_info'] = {
                'valid': True,
                'days_left': days_left,
                'expires_at': not_after_str,
                'issuer_org': issuer.get('organizationName', 'Unknown'),
                'common_name': subject.get('commonName', clean_domain)
            }
    except Exception as ssl_err:
        results['ssl_info'] = {'valid': False, 'error': str(ssl_err)}
        
    # 3. HTTP Headers & Status Code
    try:
        req = urllib.request.Request(f'https://{clean_domain}', headers={'User-Agent': 'ALFA-DomainAudit/1.0'})
        with urllib.request.urlopen(req, timeout=5.0) as resp:
            headers = dict(resp.getheaders())
            results['http_status'] = resp.status
            results['server'] = headers.get('Server', headers.get('server', 'Hidden'))
            results['content_type'] = headers.get('Content-Type', headers.get('content-type', ''))
    except Exception as http_err:
        results['http_error'] = str(http_err)
        
    results['status'] = 'success'
    return results
