import json
import os
import sqlite3
from datetime import datetime
from typing import Any

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from alfa import tools
from alfa.core import database
from alfa.dashboard.common import REPO_ROOT

router = APIRouter()

# ==================== ARTIFACTS & WORKSPACE EXPLORER ====================

WORKSPACE_ROOTS = [
    {
        "id": "workspace",
        "label": "🏠 ALFA Workspace (proyek agen)",
        "path": "~/ALFA_WORKSPACE",
    },
    {
        "id": "swarm",
        "label": "🤖 Output Swarm",
        "path": os.path.expanduser("~/Dokumen/ALFA_SWARM_OUTPUTS"),
    },
    {
        "id": "videos",
        "label": "🎬 Video Generator",
        "path": os.path.expanduser("~/Dokumen/ALFA_GENERATED_VIDEOS"),
    },
    {
        "id": "output",
        "label": "📦 Folder Output",
        "path": os.path.expanduser("~/output"),
    },
    {"id": "sandbox", "label": "⚡ Sandbox", "path": "/dev/shm/alfa_sandbox"},
]

_WS_SKIP_DIRS = {
    ".git",
    "venv",
    ".venv",
    "node_modules",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    "dist",
    "build",
    ".next",
    "target",
}
_WS_MAX_FILE_BYTES = 300_000


def _ws_real_path(path: str) -> str | None:
    """Resolve path & pastikan berada di dalam salah satu workspace root."""
    real = os.path.realpath(os.path.expanduser(path))
    for r in WORKSPACE_ROOTS:
        rp = os.path.realpath(os.path.expanduser(r["path"]))
        if real == rp or real.startswith(rp + os.sep):
            return real
    return None


def _safe_workspace_path(path: str) -> str:
    real = _ws_real_path(path)
    if not real:
        allowed = ", ".join(os.path.expanduser(r["path"]) for r in WORKSPACE_ROOTS)
        raise HTTPException(
            status_code=403,
            detail=(
                f"Akses ditolak: '{path or '(kosong)'}' di luar workspace yang diizinkan. "
                f"Root tersedia: {allowed}. "
                "Proyek di luar folder ini bisa dipindahkan ke ~/ALFA_WORKSPACE."
            ),
        )
    return real


@router.get("/api/artifacts")
async def list_artifacts():
    """List recent artifacts (images, PDFs, documents, audio) generated by tools."""
    search_dirs = [
        "/dev/shm/alfa_sandbox",
        os.path.expanduser("~/output"),
        os.path.expanduser("~/.alfa"),
    ]
    artifacts = []
    valid_exts = {
        ".png",
        ".jpg",
        ".jpeg",
        ".pdf",
        ".odt",
        ".ods",
        ".odp",
        ".docx",
        ".xlsx",
        ".pptx",
        ".mp3",
        ".mp4",
        ".csv",
        ".json",
        ".zip",
    }

    for s_dir in search_dirs:
        if os.path.exists(s_dir):
            for root, _, files in os.walk(s_dir):
                for f in files:
                    ext = os.path.splitext(f)[1].lower()
                    if ext in valid_exts:
                        full_p = os.path.join(root, f)
                        st = os.stat(full_p)
                        artifacts.append(
                            {
                                "name": f,
                                "path": full_p,
                                "size_kb": round(st.st_size / 1024, 1),
                                "modified": datetime.fromtimestamp(
                                    st.st_mtime
                                ).strftime("%Y-%m-%d %H:%M:%S"),
                                "extension": ext[1:].upper(),
                                "is_image": ext in [".png", ".jpg", ".jpeg"],
                            }
                        )

    artifacts = sorted(artifacts, key=lambda x: x["modified"], reverse=True)[:30]
    return {"status": "success", "total": len(artifacts), "artifacts": artifacts}


@router.get("/api/workspace/roots")
async def workspace_roots():
    """Daftar root proyek yang bisa dijelajahi."""
    roots = []
    for r in WORKSPACE_ROOTS:
        p = os.path.realpath(os.path.expanduser(r["path"]))
        roots.append({**r, "exists": os.path.isdir(p)})
    return {"status": "success", "roots": roots}


@router.get("/api/workspace/tree")
async def workspace_tree(path: str):
    """List satu level isi folder (lazy-load per folder klik)."""
    real = _safe_workspace_path(path)
    if not os.path.isdir(real):
        raise HTTPException(status_code=404, detail="Bukan direktori")
    items = []
    try:
        entries = sorted(
            os.scandir(real), key=lambda e: (not e.is_dir(), e.name.lower())
        )
    except PermissionError:
        raise HTTPException(status_code=403, detail="Izin dibatalkan")
    for e in entries[:400]:
        if e.name in _WS_SKIP_DIRS or e.name.startswith("."):
            continue
        try:
            st = e.stat()
            items.append(
                {
                    "name": e.name,
                    "type": "dir" if e.is_dir() else "file",
                    "size": st.st_size if e.is_file() else None,
                    "modified": datetime.fromtimestamp(st.st_mtime).strftime(
                        "%Y-%m-%d %H:%M"
                    ),
                }
            )
        except OSError:
            continue
    return {"status": "success", "path": real, "items": items}


@router.get("/api/workspace/file")
async def workspace_read_file(path: str):
    """Baca isi file teks utk dilihat di browser (dengan deteksi biner)."""
    real = _safe_workspace_path(path)
    if not os.path.isfile(real):
        raise HTTPException(status_code=404, detail="File tidak ditemukan")
    size = os.path.getsize(real)
    with open(real, "rb") as f:
        head = f.read(4096)
    is_binary = b"\x00" in head
    if is_binary:
        return {
            "status": "binary",
            "name": os.path.basename(real),
            "size": size,
            "message": "File biner — gunakan tombol Download.",
            "download_url": f"/api/artifacts/download?path={real}",
        }
    truncated = size > _WS_MAX_FILE_BYTES
    with open(real, "rb") as f:
        data = f.read(_WS_MAX_FILE_BYTES)
    return {
        "status": "success",
        "name": os.path.basename(real),
        "size": size,
        "truncated": truncated,
        "content": data.decode("utf-8", errors="replace"),
        "download_url": f"/api/artifacts/download?path={real}",
    }


@router.get("/api/artifacts/download")
async def download_artifact(path: str):
    """Safely download an artifact file (restricted to known artifact directories)."""
    import video_generator
    from alfa.swarm import engine as swarm_engine

    allowed_dirs = [
        os.path.realpath("/dev/shm/alfa_sandbox"),
        os.path.realpath(os.path.expanduser("~/output")),
        os.path.realpath(os.path.expanduser("~/.alfa")),
        os.path.realpath(os.path.expanduser("~/Dokumen/ALFA_PDF_TOOLS")),
        os.path.realpath(os.path.expanduser("~/Dokumen/ALFA_SWARM_OUTPUTS")),
        os.path.realpath(os.path.expanduser("~/Dokumen")),
        os.path.realpath(video_generator.VIDEO_OUT_DIR),
        os.path.realpath(swarm_engine.SWARM_OUTPUT_DIR),
    ]
    real_path = os.path.realpath(path)
    if not any(
        real_path == d or real_path.startswith(d + os.sep) for d in allowed_dirs
    ):
        raise HTTPException(
            status_code=403,
            detail="Akses ditolak: path di luar direktori artefak yang diizinkan.",
        )
    if not os.path.exists(real_path) or not os.path.isfile(real_path):
        raise HTTPException(status_code=404, detail="File not found")
    return FileResponse(real_path, filename=os.path.basename(real_path))


# ==================== GUARDIAN & PROACTIVE AGENT ====================


@router.get("/api/guardian/config")
async def get_guardian_config():
    """Get configuration for System Guardian & Ambient Proactive Agent."""
    g_cfg = tools.proactive_system_guardian_config("status").get("guardian", {})
    p_cfg = tools.proactive_ambient_agent_config("status").get("proactive_config", {})
    return {"status": "success", "guardian": g_cfg, "proactive": p_cfg}


@router.post("/api/guardian/config")
async def update_guardian_config(payload: dict[str, Any]):
    """Update guardian & proactive configurations."""
    if "guardian" in payload:
        g = payload["guardian"]
        tools.proactive_system_guardian_config(
            action="enable" if g.get("enabled", True) else "disable",
            cpu_threshold=g.get("cpu_threshold", 90),
            ram_threshold=g.get("ram_threshold", 85),
            disk_threshold=g.get("disk_threshold", 90),
            battery_critical=g.get("battery_critical", 10),
            auto_kill_ram_hogs=g.get("auto_kill_ram_hogs", False),
        )
    if "proactive" in payload:
        p = payload["proactive"]
        tools.proactive_ambient_agent_config(
            action="enable" if p.get("enabled", True) else "disable",
            min_hours_between_pings=p.get("min_hours_between_pings", 3),
            quiet_hours_start=p.get("quiet_hours_start", 23),
            quiet_hours_end=p.get("quiet_hours_end", 7),
        )
    return {
        "status": "success",
        "message": "Konfigurasi Guardian & Proaktif berhasil disimpan!",
    }


# ==================== VAULT & SECURITY ====================


@router.get("/api/vault/list")
async def list_vault_secrets(category: str = "all"):
    """List metadata for secrets stored in the AES-256-GCM vault."""
    from alfa.security import vault as vault_engine

    return {
        "status": "success",
        "items": vault_engine.vault.list_secrets(category=category),
    }


@router.post("/api/vault/store")
async def store_vault_secret(payload: dict[str, Any]):
    """Encrypt and store secret into AES-256-GCM vault."""
    from alfa.security import vault as vault_engine

    name = payload.get("name", "").strip()
    value = payload.get("value", "").strip()
    category = payload.get("category", "api_key").strip()
    notes = payload.get("notes", "").strip()

    if not name or not value:
        return {"status": "error", "message": "Nama dan nilai secret wajib diisi."}

    res = vault_engine.vault.store_secret(
        name=name, value=value, category=category, notes=notes
    )
    return res


@router.post("/api/vault/reveal")
async def reveal_vault_secret(payload: dict[str, Any]):
    """Decrypt and reveal a secret value for authorized viewing."""
    from alfa.security import vault as vault_engine

    secret_id = payload.get("id") or payload.get("name")
    if not secret_id:
        return {"status": "error", "message": "Secret ID atau nama diperlukan."}

    sec = vault_engine.vault.get_secret(str(secret_id))
    if not sec:
        return {"status": "error", "message": "Secret tidak ditemukan di dalam vault."}

    return {
        "status": "success",
        "name": sec["name"],
        "category": sec["category"],
        "value": sec["value"],
    }


@router.delete("/api/vault/{secret_id}")
async def delete_vault_secret(secret_id: int):
    """Delete a secret permanently from the vault."""
    from alfa.security import vault as vault_engine

    deleted = vault_engine.vault.delete_secret(int(secret_id))
    if deleted:
        return {
            "status": "success",
            "message": f"Secret ID {secret_id} berhasil dihapus dari vault.",
        }
    return {"status": "error", "message": f"Secret ID {secret_id} tidak ditemukan."}


@router.post("/api/security/audit")
async def audit_target_security(payload: dict[str, Any]):
    """Perform comprehensive defensive cybersecurity audit on a target URL."""
    from alfa.core import permissions as security_auditor

    target_url = payload.get("url", "").strip()
    if not target_url:
        return {"status": "error", "message": "URL target wajib dimasukkan."}

    res = security_auditor.audit_website_security(target_url)
    return res


@router.get("/api/security/permission-audit")
async def get_permission_audit_log(chat_id: int | None = None, limit: int = 50):
    """Get permission audit trail log."""
    db_path = os.path.join(REPO_ROOT, "agent_data.db")
    conn = sqlite3.connect(db_path, timeout=30)
    try:
        if chat_id:
            rows = conn.execute(
                """SELECT id, chat_id, tool_name, tier, decision, arguments_json, 
                          datetime(created_at, 'unixepoch', 'localtime') as timestamp, 
                          round(response_time_sec, 2) as response_time
                   FROM permission_audit 
                   WHERE chat_id=? 
                   ORDER BY created_at DESC LIMIT ?""",
                (int(chat_id), limit),
            ).fetchall()
        else:
            rows = conn.execute(
                """SELECT id, chat_id, tool_name, tier, decision, arguments_json, 
                          datetime(created_at, 'unixepoch', 'localtime') as timestamp, 
                          round(response_time_sec, 2) as response_time
                   FROM permission_audit 
                   ORDER BY created_at DESC LIMIT ?""",
                (limit,),
            ).fetchall()

        audit_logs = []
        for row in rows:
            audit_logs.append(
                {
                    "id": row[0],
                    "chat_id": row[1],
                    "tool_name": row[2],
                    "tier": row[3],
                    "decision": row[4],
                    "arguments_json": json.loads(row[5]) if row[5] else {},
                    "timestamp": row[6],
                    "response_time_sec": row[7],
                }
            )
        return {"status": "success", "logs": audit_logs, "total": len(audit_logs)}
    finally:
        conn.close()


@router.get("/api/security/trust-scores")
async def get_all_trust_scores():
    """Get trust scores for all users."""
    db_path = os.path.join(REPO_ROOT, "agent_data.db")
    conn = sqlite3.connect(db_path, timeout=30)
    try:
        rows = conn.execute(
            """SELECT chat_id, trust_score, total_approvals, safe_approvals, risky_approvals,
                      datetime(last_updated, 'unixepoch', 'localtime') as last_updated
               FROM user_trust_scores 
               ORDER BY trust_score DESC"""
        ).fetchall()

        scores = []
        for row in rows:
            scores.append(
                {
                    "chat_id": row[0],
                    "trust_score": round(row[1], 3),
                    "total_approvals": row[2],
                    "safe_approvals": row[3],
                    "risky_approvals": row[4],
                    "last_updated": row[5],
                }
            )
        return {"status": "success", "scores": scores, "total_users": len(scores)}
    finally:
        conn.close()


@router.get("/api/vault/passkey/status")
async def get_passkey_status():
    """Get status of biometric/passkey lock."""
    with database.get_sync_db() as conn:
        c = conn.cursor()
        c.execute(
            "CREATE TABLE IF NOT EXISTS system_settings (key TEXT PRIMARY KEY, value TEXT)"
        )
        c.execute(
            "SELECT value FROM system_settings WHERE key = 'passkey_lock_enabled'"
        )
        row = c.fetchone()
        enabled = row[0] == "true" if row else False
        return {"enabled": enabled}


@router.post("/api/vault/passkey/toggle")
async def toggle_passkey_lock(payload: dict[str, Any]):
    """Toggle biometric/passkey lock for the dashboard."""
    enabled = bool(payload.get("enabled", False))
    with database.get_sync_db() as conn:
        c = conn.cursor()
        c.execute(
            "CREATE TABLE IF NOT EXISTS system_settings (key TEXT PRIMARY KEY, value TEXT)"
        )
        c.execute(
            "INSERT OR REPLACE INTO system_settings (key, value) VALUES ('passkey_lock_enabled', ?)",
            ("true" if enabled else "false",),
        )
        conn.commit()
        return {
            "status": "success",
            "enabled": enabled,
            "message": f"Kunci Passkey Biometrik {'diaktifkan' if enabled else 'dinonaktifkan'}.",
        }
