"""Filesystem, workspace search, codebase indexer, git, and document tools.

Facade re-exporting from modular subpackage alfa.tools.filesystem.
"""

from alfa.tools.filesystem import *  # noqa: F401, F403
from alfa.tools.filesystem import (
    _CODE_CHUNK_LINES,
    _CODE_INDEX_DB,
    _CODE_INDEX_MAX_CHUNKS,
    _CODE_INDEX_SKIP_DIRS,
    _MAX_EDIT_FILE_BYTES,
    _chunk_code_lines,
    _code_index_connect,
    _detect_gdrive_auth_mode,
    _get_default_gdrive_folder_id,
    _get_gdrive_service,
    _index_freshness,
    _index_one_file,
    _iter_code_files,
    _py_syntax_guard,
    _resolve_host_path,
    apply_unified_diff,
    compress_folder_to_zip,
    edit_file_precise,
    find_user_files,
    gdrive_create_folder,
    gdrive_download_file,
    gdrive_list_files,
    gdrive_oauth_exchange_code,
    gdrive_oauth_get_auth_url,
    gdrive_oauth_login,
    gdrive_oauth_logout,
    gdrive_save_oauth_client_secret,
    gdrive_status,
    gdrive_sync_to_second_brain,
    gdrive_upload_file,
    git_operations,
    git_worktree_sandbox_create,
    git_worktree_sandbox_list,
    git_worktree_sandbox_rollback,
    git_worktree_sandbox_verify_and_merge,
    grep_workspace,
    index_codebase,
    libreoffice_convert_document,
    libreoffice_create_document,
    libreoffice_extract_document_text,
    libreoffice_render_page_previews,
    lsp_analyze_module_hierarchy,
    lsp_find_symbol_definition,
    lsp_find_symbol_references,
    markitdown_convert_document,
    read_local_file,
    search_codebase,
    search_workspace_files,
    send_file_to_chat,
    vault_delete_secret,
    vault_get_secret,
    vault_list_secrets,
    vault_store_secret,
    write_local_file,
)
